
#spring:
#jpa:
#show-sql: true
#h2:
#console:
#enabled: true
#
#server:
#port: 9000

spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    password: password
    username: sa

#    url: jdbc:h2:file:/data/demo
server:
  port: 9000